In [ ]:
from social_media_parser.parsers import social_media_events

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York")
t.show(10)

t.group("platform")

platform  | count
instagram | 182
tiktok    | 30872

In [ ]:
from social_media_parser.parsers import social_media_events
from social_media_parser.parsers.combined import events_by_hour, events_by_weekday, events_by_date

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York")

events_by_hour(t).show(10)
events_by_weekday(t).show()

In [ ]:
from social_media_parser.parsers import social_media_events

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York", window="1_week")
t.show(10)

In [ ]:
# --- TikTok quick test cell (paste into analysis.ipynb) ---

from src.tiktok_tables.tiktok_events import tiktok_events, tiktok_watch_summary

# 1) Build the TikTok events table
t = tiktok_events("data/user_data_tiktok.json", tz="America/New_York")

# 2) Inspect
print("Columns:", t.labels)
print("Rows:", t.num_rows)
t.show(10)

# 3) Basic breakdowns
t.group("action_type").sort("count", descending=True).show()

# 4) TikTok-only watch summary (returns dict of tables)
out = tiktok_watch_summary(t)

out["total"].show()
out["by_hour"].show(10)
out["by_weekday"].show()
out["by_date"].show(10)

# 5) Optional: only watch events table (useful for plotting)
watch = t.where("action_type", "watch")
watch.show(10)

Columns: ('platform', 'object_type', 'action_type', 'username', 'target', 'value', 'timestamp', 'timestamp_dt', 'hour', 'weekday', 'date')
Rows: 30872

In [ ]:
# --- TikTok quick test cell (paste into analysis.ipynb) ---

from src.tiktok_tables.tiktok_events import (
    tiktok_events,
    tiktok_watch_summary,
    tiktok_late_night_binge,
    tiktok_doomscroll_indicator,
)

# 1) Build the TikTok events table
t = tiktok_events("data/user_data_tiktok.json", tz="America/New_York")

# 2) Inspect
print("Columns:", t.labels)
print("Rows:", t.num_rows)
t.show(10)

# 3) Basic breakdowns
t.group("action_type").sort("count", descending=True).show()

# 4) TikTok-only watch summary (returns dict of tables)
out = tiktok_watch_summary(t)
out["total"].show()
out["by_hour"].show(10)
out["by_weekday"].show()
out["by_date"].show(10)

# 5) Optional: only watch events table (useful for plotting)
watch = t.where("action_type", "watch")
watch.show(10)

# 6) NEW: Late-night binge scrolling
binge = tiktok_late_night_binge(t, start_hour=23, end_hour=4, window="3_month")
binge["summary"].show()
binge["late_by_date"].show(10)

# 7) NEW: Doomscroll indicator
doom = tiktok_doomscroll_indicator(t, window="3_month", session_gap_minutes=20, top_n_days=10)
doom["summary"].show()
doom["day_scores"].show(10)

Columns: ('platform', 'object_type', 'action_type', 'username', 'target', 'value', 'timestamp', 'timestamp_dt', 'hour', 'weekday', 'date')
Rows: 30872

In [13]:
from social_media_parser.parsers.instagram import parse_instagram
from social_media_parser.parsers.combined import events_by_hour, events_by_weekday, events_by_date

t = parse_instagram("data", tz="America/New_York")

events_by_hour(t).show(10)
events_by_weekday(t).show()
events_by_date(t).show()

In [1]:
from social_media_parser.parsers.instagram import parse_instagram

t = parse_instagram("data", tz="America/New_York")
t.show(10)