In [1]:
from social_media_parser.parsers import social_media_events

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York")
t.show(10)

In [2]:
from social_media_parser.parsers import social_media_events

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York")
t.show(10)

t.group("platform")

platform  | count
instagram | 182
tiktok    | 30872

In [1]:
from social_media_parser.parsers import social_media_events
from social_media_parser.parsers.combined import events_by_hour, events_by_weekday, events_by_date

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York")

events_by_hour(t).show(10)
events_by_weekday(t).show()

In [1]:
from social_media_parser.parsers import social_media_events

t = social_media_events("data", "data/user_data_tiktok.json", tz="America/New_York", window="1_week")
t.show(10)

In [8]:
# --- TikTok quick test cell (paste into analysis.ipynb) ---

from src.tiktok_tables.tiktok_events import tiktok_events, tiktok_watch_summary

# 1) Build the TikTok events table
t = tiktok_events("data/user_data_tiktok.json", tz="America/New_York")

# 2) Inspect
print("Columns:", t.labels)
print("Rows:", t.num_rows)
t.show(10)

# 3) Basic breakdowns
t.group("action_type").sort("count", descending=True).show()

# 4) TikTok-only watch summary (returns dict of tables)
out = tiktok_watch_summary(t)

out["total"].show()
out["by_hour"].show(10)
out["by_weekday"].show()
out["by_date"].show(10)

# 5) Optional: only watch events table (useful for plotting)
watch = t.where("action_type", "watch")
watch.show(10)

Columns: ('platform', 'object_type', 'action_type', 'username', 'target', 'value', 'timestamp', 'timestamp_dt', 'hour', 'weekday', 'date')
Rows: 30872

In [ ]:
t_pt = tiktok_events("data/user_data_tiktok.json", tz="America/Los_Angeles")
t_pt.show(5)

In [ ]:
# Daily watch volume (line)
watch = data["Your Activity"]["Watch History"]["VideoList"]
df_watch = pd.DataFrame(watch)

df_watch["dt_ny"] = to_ny(df_watch["Date"])
daily_watch = df_watch.groupby(df_watch["dt_ny"].dt.date).size().reset_index(name="videos_watched")
daily_watch.rename(columns={"dt_ny":"Date"}, inplace=True)

daily_watch.head(10)

daily_watch.plot(x="Date", y="videos_watched", kind="line")
plt.title("TikTok Watch History: Videos Watched Per Day")
plt.xlabel("Date")
plt.ylabel("Watch events (rows)")
plt.show()

In [ ]:
# Weekly Bars 

# Weekly totals bar chart (labels as dates only)
weekly_watch = (
    df_watch.assign(week_start=df_watch["dt_ny"].dt.to_period("W").dt.start_time)
    .groupby("week_start").size().reset_index(name="videos_watched")
)

# Convert to date-only labels
weekly_watch["week_start_date"] = weekly_watch["week_start"].dt.date.astype(str)

weekly_watch.plot(x="week_start_date", y="videos_watched", kind="bar")
plt.title("TikTok Watch History: Videos Watched Per Week")
plt.xlabel("Week starting")
plt.ylabel("Watch events (rows)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [ ]:
#Heatmap: day vs hour (watching)
#Shows: when you watch (time-of-day patterns + daily routine).
temp = df_watch.dropna(subset=["dt_ny"]).copy()
temp["date"] = temp["dt_ny"].dt.date
temp["hour"] = temp["dt_ny"].dt.hour

# Build the date x hour grid (counts)
pivot = temp.pivot_table(index="date", columns="hour", values="Date", aggfunc="count", fill_value=0)

# Smooth across days (3-day rolling average)
pivot_smooth = pivot.rolling(window=3, min_periods=1).mean()

plt.figure(figsize=(12, 6))
plt.imshow(pivot_smooth.values, aspect="auto")
plt.title("Watch History Heatmap (3-Day, NY Time)")
plt.xlabel("Hour of day")
plt.ylabel("Date")
plt.xticks(range(24), range(24))
step = max(1, len(pivot_smooth.index)//10)
plt.yticks(range(0, len(pivot_smooth.index), step), [str(d) for d in pivot_smooth.index[::step]])
plt.colorbar(label="Avg watch events")
plt.show()

In [ ]:
#Day-of-week boxplot (watch events/day)
daily_watch_dt = pd.to_datetime(daily_watch["Date"])
daily_watch["dow"] = daily_watch_dt.dt.day_name()

order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
groups = [daily_watch.loc[daily_watch["dow"]==d, "videos_watched"] for d in order]

plt.figure(figsize=(10,5))
plt.boxplot(groups, labels=order, showfliers=False)
plt.title("Watch Events per Day by Day of Week")
plt.xlabel("Day of week")
plt.ylabel("Watch events (rows)")
plt.xticks(rotation=30)
plt.show()

In [ ]:
#Sessions per day + avg session length
temp = df_watch.dropna(subset=["dt_ny"]).sort_values("dt_ny").copy()
temp["prev"] = temp["dt_ny"].shift(1)
temp["gap_min"] = (temp["dt_ny"] - temp["prev"]).dt.total_seconds() / 60
temp["new_session"] = (temp["gap_min"].isna()) | (temp["gap_min"] > 30)
temp["session_id"] = temp["new_session"].cumsum()

sessions = (
    temp.groupby("session_id")
    .agg(start=("dt_ny","min"), end=("dt_ny","max"), events=("dt_ny","size"))
    .reset_index()
)
sessions["session_minutes"] = (sessions["end"] - sessions["start"]).dt.total_seconds() / 60
sessions["date"] = sessions["start"].dt.date

session_daily = sessions.groupby("date").agg(
    sessions_per_day=("session_id","nunique"),
    avg_session_minutes=("session_minutes","mean"),
    total_watch_events=("events","sum"),
).reset_index()

session_daily.head(10)

In [ ]:
#Likes per day overlaid with watches per day
#This shows active engagement vs consumption.
likes = data["Likes and Favorites"]["Like List"]["ItemFavoriteList"]
df_like = pd.DataFrame(likes)

df_like["dt_ny"] = to_ny(df_like["date"])
daily_like = df_like.groupby(df_like["dt_ny"].dt.date).size().reset_index(name="likes")
daily_like.rename(columns={"dt_ny":"Date"}, inplace=True)

combined = pd.merge(daily_watch, daily_like, on="Date", how="outer").fillna(0)
combined.head(10)
combined.plot(x="Date", y=["videos_watched","likes"], kind="line")
plt.title("Watches vs Likes Per Day")
plt.xlabel("Date")
plt.ylabel("Count")
plt.show()

In [ ]:
#Engagement rate over time (likes / watches)
#This shows whether you’re becoming more interactive over time.
import pandas as pd
import matplotlib.pyplot as plt


# Ensure Date is datetime
combined["Date"] = pd.to_datetime(combined["Date"], errors="coerce")

# Ensure numeric
combined["likes"] = pd.to_numeric(combined["likes"], errors="coerce")
combined["videos_watched"] = pd.to_numeric(combined["videos_watched"], errors="coerce")

# Convert cutoff (like start date) to datetime
cutoff = pd.to_datetime(daily_like["Date"].min())

# Filter to dates where likes data exists (no forced zeros)
plot_df = combined[combined["Date"] >= cutoff].copy()

# Engagement rate
plot_df["engagement_rate"] = plot_df["likes"] / plot_df["videos_watched"].replace(0, pd.NA)

plot_df = plot_df.dropna(subset=["engagement_rate"]).sort_values("Date")

plot_df.plot(x="Date", y="engagement_rate", kind="line")
plt.title("Engagement Rate Over Time (Likes / Watch Events)")
plt.xlabel("Date")
plt.ylabel("Likes per watch event")
plt.show()

In [ ]:
searches = data["Your Activity"]["Searches"]["SearchList"]
df_search = pd.DataFrame(searches)

# TikTok exports sometimes use "Date" and "SearchTerm" (or similar).
df_search["dt_ny"] = to_ny(df_search["Date"])

daily_search = df_search.groupby(df_search["dt_ny"].dt.date).size().reset_index(name="searches")
daily_search.rename(columns={"dt_ny":"Date"}, inplace=True)
daily_search.head(10)

daily_search.plot(x="Date", y="searches", kind="line")
plt.title("Searches Per Day")
plt.xlabel("Date")
plt.ylabel("Search events")
plt.show()

In [ ]:
# Try common field names
term_col = None
for c in df_search.columns:
    if "search" in c.lower() and c.lower() != "date":
        term_col = c
        break

term_col

top_terms = df_search[term_col].value_counts().head(15).reset_index()
top_terms.columns = ["term", "count"]

top_terms.plot(x="term", y="count", kind="bar")
plt.title("Top Search Terms (Top 15)")
plt.xlabel("Term")
plt.ylabel("Count")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [ ]:
#To messy
top5 = df_search[term_col].value_counts().head(5).index.tolist()
temp = df_search[df_search[term_col].isin(top5)].copy()
temp["date"] = temp["dt_ny"].dt.date

trend = temp.groupby(["date", term_col]).size().unstack(fill_value=0).reset_index()
trend.head(10)
trend.plot(x="date", kind="line")
plt.title("Top 5 Search Terms Over Time (Daily)")
plt.xlabel("Date")
plt.ylabel("Searches")
plt.show()

In [ ]:
combo2 = pd.merge(daily_watch, daily_search, on="Date", how="inner")
combo2.plot(x="videos_watched", y="searches", kind="scatter")
plt.title("Searches vs Watch Events (Daily)")
plt.xlabel("Watch events per day")
plt.ylabel("Searches per day")
plt.show()

In [ ]:

#Comments per day

comments = data["Comment"]["Comments"]["CommentsList"]
df_com = pd.DataFrame(comments)

df_com["dt_ny"] = to_ny(df_com["date"])
daily_com = df_com.groupby(df_com["dt_ny"].dt.date).size().reset_index(name="comments")
daily_com.rename(columns={"dt_ny":"Date"}, inplace=True)

daily_com.plot(x="Date", y="comments", kind="line")
plt.title("Comments Per Day")
plt.xlabel("Date")
plt.ylabel("Comments")
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

daily_like["Date"] = pd.to_datetime(daily_like["Date"], errors="coerce")
daily_com["Date"]  = pd.to_datetime(daily_com["Date"], errors="coerce")

combo3 = pd.merge(daily_like, daily_com, on="Date", how="outer").fillna(0)

combo3["likes"] = pd.to_numeric(combo3["likes"], errors="coerce").fillna(0)
combo3["comments"] = pd.to_numeric(combo3["comments"], errors="coerce").fillna(0)

# Replace 0 likes with 1 so we can compute a finite ratio
combo3["comment_like_ratio"] = combo3["comments"] / combo3["likes"].replace(0, 1)

combo3 = combo3.sort_values("Date")

combo3.plot(x="Date", y="comment_like_ratio", kind="line")
plt.title("Comment-to-Like Ratio Over Time (0 likes treated as 1)")
plt.xlabel("Date")
plt.ylabel("Comments per like (adjusted)")
plt.show()

In [ ]:
import re
from collections import Counter

text_col = None
for c in df_com.columns:
    if "comment" in c.lower() or "content" in c.lower() or "text" in c.lower():
        text_col = c
        break

text_col

def tokenize(s):
    s = str(s).lower()
    s = re.sub(r"http\S+", "", s)
    words = re.findall(r"[a-z']+", s)
    stop = set(["the","and","for","that","with","this","you","your","was","are","but","not","have","just","its","i","im","to","of","in","it","on","a","is"])
    return [w for w in words if w not in stop and len(w) > 2]

counter = Counter()
for t in df_com[text_col].dropna().head(5000):
    counter.update(tokenize(t))

top_words = pd.DataFrame(counter.most_common(15), columns=["word","count"])
top_words.plot(x="word", y="count", kind="bar")
plt.title("Top Words in Comments (Top 15)")
plt.xlabel("Word")
plt.ylabel("Count")
plt.xticks(rotation=30)
plt.show()

In [ ]:
# Aggregate all DM chats into one DataFrame
chats = data["Direct Message"]["Direct Messages"]["ChatHistory"]
all_msgs = []
for conv_name, msgs in chats.items():
    if isinstance(msgs, list):
        for m in msgs:
            m2 = dict(m)
            m2["conversation"] = conv_name
            all_msgs.append(m2)

df_dm = pd.DataFrame(all_msgs)
df_dm["dt_ny"] = to_ny(df_dm["Date"])

daily_dm = df_dm.groupby(df_dm["dt_ny"].dt.date).size().reset_index(name="messages")
daily_dm.rename(columns={"dt_ny":"Date"}, inplace=True)

daily_dm.plot(x="Date", y="messages", kind="line")
plt.title("DM Messages Per Day")
plt.xlabel("Date")
plt.ylabel("Messages")
plt.show()
weekly_dm = (
    df_dm.assign(week=df_dm["dt_ny"].dt.to_period("W").dt.start_time)
    .groupby("week").size().reset_index(name="messages")
)
weekly_dm.plot(x="week", y="messages", kind="bar")
plt.title("DM Messages Per Week")
plt.xlabel("Week starting")
plt.ylabel("Messages")
plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.dates as mdates

monthly_dm = (
    df_dm.dropna(subset=["dt_ny"])
    .assign(month=df_dm["dt_ny"].dt.to_period("M").dt.to_timestamp())
    .groupby("month").size().reset_index(name="messages")
).sort_values("month")

plt.figure(figsize=(12,5))
plt.plot(monthly_dm["month"], monthly_dm["messages"])
plt.title("DM Messages Per Month")
plt.xlabel("Month")
plt.ylabel("Messages")

ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.dates as mdates

weekly_dm = (
    df_dm.dropna(subset=["dt_ny"])
    .assign(week_start=df_dm["dt_ny"].dt.to_period("W").dt.start_time)
    .groupby("week_start").size().reset_index(name="messages")
)

weekly_dm = weekly_dm.sort_values("week_start")

plt.figure(figsize=(12,5))
plt.plot(weekly_dm["week_start"], weekly_dm["messages"])
plt.title("DM Messages Per Week")
plt.xlabel("Week")
plt.ylabel("Messages")

ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))      # label every 3 months
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Make sure dt_ny exists
df_dm["dt_ny"] = to_ny(df_dm["Date"])

# Mark link messages
df_dm["is_link"] = df_dm["Content"].astype(str).str.contains("http", na=False)

# Daily link share rate
daily_link_rate = (
    df_dm.groupby(df_dm["dt_ny"].dt.date)
    .agg(total_msgs=("is_link", "size"), link_msgs=("is_link", "sum"))
    .reset_index()
)

daily_link_rate.rename(columns={"dt_ny": "Date"}, inplace=True)  # this works because groupby key becomes dt_ny column name
daily_link_rate["link_share_rate"] = daily_link_rate["link_msgs"] / daily_link_rate["total_msgs"]

# Plot (use Date, not dt_ny)
daily_link_rate.plot(x="Date", y="link_share_rate", kind="line")
plt.title("DM Link Share Rate Per Day (Links / Total Messages)")
plt.xlabel("Date")
plt.ylabel("Share rate")
plt.show()